package banking.ui;

import java.awt.Color;

import banking.factory.entity.BankAccountFactory;
import banking.factory.entity.BankAccountType;
import framework.entity.Account;
import framework.entity.Address;
import framework.entity.Customer;
import framework.facade.BankAccountFacade;
import framework.factory.entity.AccountFactory;
import framework.factory.entity.CustomerFactory;
import framework.factory.entity.CustomerType;

/*
		A basic implementation of the JDialog class.
*/

public class JDialog_AddPAcc extends javax.swing.JDialog {
	private BankFrm parentframe;
	private BankAccountFacade bankaccountfacade= new BankAccountFacade();
	private Account account;
	private Customer customer;
	private AccountFactory accountFactory = new BankAccountFactory();
	int facadereturn;

	public JDialog_AddPAcc(BankFrm parent) {
		super(parent);
		parentframe = parent;

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		// {{INIT_CONTROLS
		setTitle("Add personal account");
		setModal(true);
		getContentPane().setLayout(null);
		setSize(600, 400);
		getContentPane().setBackground(new Color(95,95,95));
		//.setForeground(Color.WHITE);
		setVisible(false);
		JRadioButton_Chk.setText("Checkings");
		JRadioButton_Chk.setActionCommand("Checkings");
		JRadioButton_Chk.setForeground(java.awt.Color.white);
		JRadioButton_Chk.setBackground(new Color(95,95,95));
		getContentPane().add(JRadioButton_Chk);
		JRadioButton_Chk.setBounds(36, 0, 84, 24);
		JRadioButton_Sav.setText("Savings");
		JRadioButton_Sav.setActionCommand("Savings");
		JRadioButton_Sav.setForeground(java.awt.Color.white);
		JRadioButton_Sav.setBackground(new Color(95,95,95));
		getContentPane().add(JRadioButton_Sav);
		JRadioButton_Sav.setBounds(36, 24, 84, 24);
		JLabelv5.setBounds(150, 30, 150, 20 );
		JLabelv5.setText("");
		JLabelv5.setForeground(Color.RED);
		getContentPane().add(JLabelv5);
		JLabel1.setText("Name");
		getContentPane().add(JLabel1);
		JLabel1.setForeground(java.awt.Color.white);
		JLabel1.setBounds(12, 84, 48, 24);
		JLabel2.setText("Street");
		getContentPane().add(JLabel2);
		JLabel2.setForeground(java.awt.Color.white);
		JLabel2.setBounds(12, 108, 48, 24);
		JLabel3.setText("City");
		getContentPane().add(JLabel3);
		JLabel3.setForeground(java.awt.Color.white);
		JLabel3.setBounds(12, 132, 48, 24);
		JLabel4.setText("State");
		getContentPane().add(JLabel4);
		JLabel4.setForeground(java.awt.Color.white);
		JLabel4.setBounds(12, 156, 48, 24);
		JLabel5.setText("Zip");
		getContentPane().add(JLabel5);
		JLabel5.setForeground(java.awt.Color.white);
		JLabel5.setBounds(12, 180, 48, 24);
		JLabel6.setText("Birthdate");
		getContentPane().add(JLabel6);
		JLabel6.setForeground(java.awt.Color.white);
		JLabel6.setBounds(12, 204, 96, 24);
		JLabel7.setText("Email");
		getContentPane().add(JLabel7);
		JLabel7.setForeground(java.awt.Color.white);
		JLabel7.setBounds(12, 228, 48, 24);
		getContentPane().add(JTextField_NAME);
		JTextField_NAME.setBounds(84, 84, 156, 20);
		getContentPane().add(JTextField_CT);
		
		JLabelv2.setBounds(250, 84, 150, 20 );
		JLabelv2.setText("");
		JLabelv2.setForeground(Color.RED);
		getContentPane().add(JLabelv2);
		JTextField_CT.setBounds(84, 132, 156, 20);
		getContentPane().add(JTextField_ST);
		JTextField_ST.setBounds(84, 156, 156, 20);
		getContentPane().add(JTextField_STR);
		JTextField_STR.setBounds(84, 108, 156, 20);
		getContentPane().add(JTextField_ZIP);
		JTextField_ZIP.setBounds(84, 180, 156, 20);
		getContentPane().add(JTextField_BD);
		JTextField_BD.setBounds(84, 204, 156, 20);
		
		
		getContentPane().add(JTextField_EM);
		JTextField_EM.setBounds(84, 228, 156, 20);
		
		JLabelv3.setBounds(250, 228, 150, 20 );
		JLabelv3.setText("");
		JLabelv3.setForeground(Color.RED);
		getContentPane().add(JLabelv3);
		JButton_OK.setText("OK");
		JButton_OK.setActionCommand("OK");
		getContentPane().add(JButton_OK);
		JButton_OK.setBounds(48, 264, 84, 24);
		JButton_Cancel.setText("Cancel");
		JButton_Cancel.setActionCommand("Cancel");
		getContentPane().add(JButton_Cancel);
		JButton_Cancel.setBounds(156, 264, 84, 24);
		getContentPane().add(JTextField_ACNR);
		JTextField_ACNR.setBounds(84, 60, 156, 20);
		JLabel8.setText("Acc Nr");
		
		
		getContentPane().add(JLabel8);
		JLabel8.setForeground(java.awt.Color.white);
		JLabel8.setBounds(12, 60, 48, 24);
		// }}

		// {{REGISTER_LISTENERS
		SymMouse aSymMouse = new SymMouse();
		JRadioButton_Chk.addMouseListener(aSymMouse);
		JRadioButton_Sav.addMouseListener(aSymMouse);
		SymAction lSymAction = new SymAction();
		JButton_OK.addActionListener(lSymAction);
		JButton_Cancel.addActionListener(lSymAction);
		// }}
	}

	// {{DECLARE_CONTROLS
	javax.swing.JRadioButton JRadioButton_Chk = new javax.swing.JRadioButton();
	javax.swing.JRadioButton JRadioButton_Sav = new javax.swing.JRadioButton();
	javax.swing.JLabel JLabel1 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel2 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel3 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel4 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel5 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel6 = new javax.swing.JLabel();
	javax.swing.JLabel JLabel7 = new javax.swing.JLabel();
	javax.swing.JLabel JLabelv1 = new javax.swing.JLabel();
	javax.swing.JLabel JLabelv2 = new javax.swing.JLabel();
	javax.swing.JLabel JLabelv3 = new javax.swing.JLabel();
	javax.swing.JLabel JLabelv4 = new javax.swing.JLabel();
	javax.swing.JLabel JLabelv5 = new javax.swing.JLabel();
	
	javax.swing.JTextField JTextField_NAME = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_CT = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_ST = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_STR = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_ZIP = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_BD = new javax.swing.JTextField();
	javax.swing.JTextField JTextField_EM = new javax.swing.JTextField();
	javax.swing.JButton JButton_OK = new javax.swing.JButton();
	javax.swing.JButton JButton_Cancel = new javax.swing.JButton();
	javax.swing.JTextField JTextField_ACNR = new javax.swing.JTextField();
	javax.swing.JLabel JLabel8 = new javax.swing.JLabel();
	// }}

	class SymMouse extends java.awt.event.MouseAdapter {
		public void mouseClicked(java.awt.event.MouseEvent event) {
			Object object = event.getSource();
			if (object == JRadioButton_Chk)
				JRadioButtonChk_mouseClicked(event);
			else if (object == JRadioButton_Sav)
				JRadioButtonSav_mouseClicked(event);
		}
	}

	void JRadioButtonChk_mouseClicked(java.awt.event.MouseEvent event) {
		// When Checking radio is clicked make this radio on
		// and make Saving account radio off
		JRadioButton_Chk.setSelected(true);
		JRadioButton_Sav.setSelected(false);
	}

	void JRadioButtonSav_mouseClicked(java.awt.event.MouseEvent event) {
		// When Saving radio is clicked make this radio on
		// and make Checking account radio off
		JRadioButton_Chk.setSelected(false);
		JRadioButton_Sav.setSelected(true);

	}

	class SymAction implements java.awt.event.ActionListener {
		public void actionPerformed(java.awt.event.ActionEvent event) {
			Object object = event.getSource();
			if (object == JButton_OK)
				JButtonOK_actionPerformed(event);
			else if (object == JButton_Cancel)
				JButtonCalcel_actionPerformed(event);
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event) {
		customer=CustomerFactory.createCustomer(CustomerType.INDIVIDUAL);
		Address address= new Address();
		customer.setAddress(address);
		if (JRadioButton_Chk.isSelected()){
			
		account=accountFactory.createAccount(BankAccountType.CHECKING);	
		account.setAccountType(BankAccountType.CHECKING);
		
		account.setCustomer(customer);
		
		}
		else if(JRadioButton_Sav.isSelected()){
			
			account=accountFactory.createAccount(BankAccountType.SAVING);
			account.setAccountType(BankAccountType.SAVING);
			account.setCustomer(customer);
			}
		
		
		if(account!=null){
			
		account.setAccountNumber(JTextField_ACNR.getText());
		
		account.getCustomer().setName(JTextField_NAME.getText());
		account.getCustomer().getAddress().setStreet(JTextField_STR.getText());
		account.getCustomer().getAddress().setCity(JTextField_CT.getText());
		account.getCustomer().getAddress().setZip(JTextField_ZIP.getText());
		account.getCustomer().getAddress().setState(JTextField_ST.getText());
		//account.getCustomer().setBirthDate(JTextField_BD.getText());
		account.getCustomer().setEmail(JTextField_EM.getText());
	     facadereturn=bankaccountfacade.validateform(account);

	
		
	}else{
		JLabelv5.setText("choose account type!");
	}
		
		
		if(facadereturn==5){
			parentframe.accountnr = JTextField_ACNR.getText();
			
			parentframe.clientName = JTextField_NAME.getText();
			parentframe.street = JTextField_STR.getText();
			parentframe.city = JTextField_CT.getText();
			parentframe.zip = JTextField_ZIP.getText();
			parentframe.state = JTextField_ST.getText();
			if (JRadioButton_Chk.isSelected()){
				parentframe.accountType = BankAccountType.CHECKING;
			
			}
			else if(JRadioButton_Sav.isSelected()){
				parentframe.accountType = BankAccountType.SAVING;
				
				}
			parentframe.newaccount = true;
			
			dispose();
		}else{
			switch(facadereturn) {
			   case 1 :
				   JLabelv2.setText("name field required");
			      break; // optional
			   
			   case 2 :
				   JLabelv3.setText("email field required");
			      break; // optional
			   
		
			}
		}
	}

	void JButtonCalcel_actionPerformed(java.awt.event.ActionEvent event) {
		// make this frame invisible if Cancel button is clicked
		dispose();
	}
}